[workspace]
members = ["apps/*", "libs/*"]
# https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
resolver = "3"

[workspace.dependencies]
clap = "4.5.57"
helpers = { path = "libs/helpers" }
